# service-microservice-a.yaml
apiVersion: v1
kind: Service
metadata:
  name: microservice-b
spec:
  selector:
    app: microservice-b
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: ClusterIP